# -*- coding: utf-8 -*-
"""Unemployment analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uX6dOxN2n4kIZ7jW65wbHJNLH0Iy3YvK

# .....OASIS INFOBYTE....

# ...UNEMPLOYEMENT ANALYSIS ....TASK-2....

Unemployment Analysis using Python
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

"""# Importing data"""

data = pd.read_csv("Unemployment in India.csv")
data = pd.read_csv("Unemployment_Rate_upto_11_2020.csv")
data.head()

"""# Analyzing dataset"""

data.isnull().sum()
data.columns = ['State','Date','Frequency','Unemployment Rate','Employed','Labour Participation Rate','Region','Longitude','Latitude']
data.describe()

"""# Data Visualization-Graphs"""

sns.histplot(x='Employed',hue="State",data=data)
plt.show()
plt.figure(figsize=(8,7))
plt.title('Unemployment_data_')
sns.histplot(x='Unemployment Rate',hue="State",data=data)
plt.show()

# sunburst chart for vizualization

up = data[['State','Region','Unemployment Rate']]
figure= px.sunburst(up, path=['Region','State'], values='Unemployment Rate',width=700,height=700,color_continuous_scale='magma',title='Unemployment Rate in India')
figure.show()

"""## checking the correlation of variables"""

data.corr()
cor= data.corr()
fig, ax=plt.subplots(figsize=(5,5))
sns.heatmap(cor,annot=True,ax=ax,cmap="copper")